export const IPC_MESSAGES = {
  SIGNOUT: 'SIGNOUT',
  SIGNIN: 'SIGNIN',
  APP_QUIT: 'APP_QUIT',
  STORE_SESSION: 'STORE_SESSION',
  STORE_USER: 'STORE_USER',
  RESTORE_SESSION: 'RESTORE_SESSION',
  CLEAR_STORAGE: 'CLEAR_STORAGE'
};